require:
  - rubocop-performance
  - rubocop-rails

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.1
  Exclude:
    - 'Rakefile'
    - 'doc/plugins/**'

Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Naming/FileName:
  Exclude:
      - 'db/seeds.d/*'

Style/WordArray:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false
  SupportedStyles:
    - ruby19
    - hash_rockets

Layout/LineLength:
  Max: 190

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'lib/**/engine.rb'
    - 'test/**/*'

Performance/FixedSize:
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/**/engine.rb'
    - 'test/**/*'

Naming/MethodName:
  Exclude:
    - 'app/models/concerns/orchestration/monitoring.rb'

Style/SymbolArray:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false
