name: CI

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rubocop:
    uses: theforeman/actions/.github/workflows/rubocop.yml@v0
    with:
      command: bundle exec rubocop

  test:
    name: Ruby
    needs: rubocop
    strategy:
      fail-fast: false
      matrix:
        foreman:
          - 'develop'
          - '3.9-stable'
          - '3.8-stable'
    uses: theforeman/actions/.github/workflows/foreman_plugin.yml@v0
    with:
      plugin: foreman_monitoring
      foreman_version: ${{ matrix.foreman }}
